"""create bookshelves table

Revision ID: 1821fe006433
Revises: 981c2baab82e
Create Date: 2024-01-08 14:23:37.850142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1821fe006433'
down_revision = '981c2baab82e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookshelf_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_books_bookshelf_id_bookshelves'), 'bookshelves', ['bookshelf_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_books_coverart_id_coverarts'), 'coverarts', ['coverart_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_books_coverart_id_coverarts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_books_bookshelf_id_bookshelves'), type_='foreignkey')
        batch_op.drop_column('bookshelf_id')

    # ### end Alembic commands ###
