"""create bookshelves table

Revision ID: 3ccfddd40b69
Revises: 981c2baab82e
Create Date: 2024-01-08 07:15:28.354575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ccfddd40b69'
down_revision = '981c2baab82e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookshelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookshelf_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bookshelves', ['bookshelf_id'], ['id'])
        batch_op.create_foreign_key(None, 'coverarts', ['coverart_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bookshelf_id')

    op.drop_table('bookshelves')
    # ### end Alembic commands ###
