"""add bookshelves table

Revision ID: c9ac12cc4b4d
Revises: e6c4d696034e
Create Date: 2024-01-08 15:01:48.687034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ac12cc4b4d'
down_revision = 'e6c4d696034e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookshelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookshelves'))
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookshelf_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_books_bookshelf_id_bookshelves'), 'bookshelves', ['bookshelf_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_books_bookshelf_id_bookshelves'), type_='foreignkey')
        batch_op.drop_column('bookshelf_id')

    op.drop_table('bookshelves')
    # ### end Alembic commands ###
