"""add coverarts table

Revision ID: e6c4d696034e
Revises: 1f82af08e781
Create Date: 2024-01-08 14:59:24.666588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c4d696034e'
down_revision = '1f82af08e781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverarts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coverarts'))
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coverart_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_books_coverart_id_coverarts'), 'coverarts', ['coverart_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_books_coverart_id_coverarts'), type_='foreignkey')
        batch_op.drop_column('coverart_id')

    op.drop_table('coverarts')
    # ### end Alembic commands ###
